DentalApp/Models/Appointment.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace DentalApp.Models
{
    public class Appointment
    {
        public int AppointmentID { get; set; }
        public string UserName { get; set; }

        //[DataType(DataType.Time)]
        [DisplayFormat(DataFormatString = "{0:dd-MM-yyyy}", ApplyFormatInEditMode = true)]
        [Display(Name = "Appointment Start")]
        public DateTime? AppointmentStart { get; set; }

        //[DataType(DataType.Time)]
        [DisplayFormat(DataFormatString = "{0:dd-MM-yyyy}", ApplyFormatInEditMode = true)]
        [Display(Name = "Appointment Finish")]
        public DateTime? AppointmentFinish { get; set; }

        // navigation properties - wizyta może dotyczyć tylko jednego lekarza i pacjenta (lekarz przyjmuje jednego pacjenta)
        // podcza wizyty przyjmuje jeden lekarz
        public int EmployeeID { get; set; }
        public Employee Employee { get; set; }
        public string EmployeeEmail { get; set; }

    }
}

DentalApp/ViewModels/AppointmentViewModel.cs
using DentalApp.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace DentalApp.ViewModels
{
    public class AppointmentViewModel
    {
        public AppointmentViewModel()

        {
            Users = new List<string>();
        }

        public int AppointmentID { get; set; }
        public Employee Employee { get; set; }
        public int EmployeeID { get; set; }
        public string Specialty { get; set; }
        public string UserName { get; set; }
        public string UserID { get; set; }

        public int AppointmentCount { get; set; }

        [Required(ErrorMessage = "Please provide date of appointment")]
        [Display(Name = "Appointment Start")]
        public DateTime? AppointmentStart { get; set; }

        public DateTime? AppointmentFinish { get; set; }

        public List<string> Users { get; set; }

        public bool IsSelected { get; set; }

        public string EmployeeEmail { get; set; }
    }
}

DentalApp/Controllers/AppointmentController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using DentalApp.DataContext;
using DentalApp.Models;
using DentalApp.Repositories;
using DentalApp.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Rotativa.AspNetCore;

namespace DentalApp.Controllers
{
    public class AppointmentController : Controller
    {
        // atrybut readonly uniemożliwia przypadkowe nadanie nowej wartości polu
        private readonly IAppointmentRepository _appointmentRepository;
        private readonly IEmployeeRepository _employeeRepository;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly ApplicationDbContext _context;
        public AppointmentController(IAppointmentRepository appointmentRepository, IEmployeeRepository employeeRepository,
            UserManager<ApplicationUser> userManager, SignInManager<ApplicationUser> signInManager, ApplicationDbContext context)
        {
            _appointmentRepository = appointmentRepository;
            _employeeRepository = employeeRepository; 
            _userManager = userManager;
            _signInManager = signInManager;
            _context = context;
        }

        // Tutaj wyświetlam wszystkie wizyty
        [Authorize(Roles ="Admin")]
        public ViewResult GetAllAppointments()
        {
            var model = _appointmentRepository.GetAllAppointments()
                .OrderByDescending(p => p.AppointmentStart);
            ViewBag.TerazJest = DateTime.Now;
            return View(model);
        }

        //Wizytę umawia Pacjent - get
        [HttpGet]
        [Authorize]
        public ViewResult CreateAppointment(int id)
        {
            AppointmentViewModel appointment = new AppointmentViewModel();
            appointment.EmployeeID = _employeeRepository.GetEmployee(id).EmployeeID;
            appointment.EmployeeEmail = _employeeRepository.GetEmployee(id).Email;
            //parsowanie do int
            appointment.UserID = _userManager.GetUserId(User);
            return View(appointment);
        }


        // Wizytę umawia Pacjent - post - kiedy wybieram datę i godzinę spotkania i naciskam - Umawiam - wywołuję metodę post
        [HttpPost]
        [Authorize]
        public RedirectToActionResult CreateAppointment(AppointmentViewModel appointment)
        {
            if (appointment.AppointmentStart < DateTime.Now)
            {
                return RedirectToAction("AppointmentLate");
            }

            else if (_context.Appointments.Where(x =>
            x.AppointmentStart == appointment.AppointmentStart &&
            x.Employee.EmployeeID == appointment.Employee.EmployeeID).Any())
            {
                return RedirectToAction("AppointmentExists");
            }

            else
            {
                Models.Appointment appointmentModel = new Models.Appointment();

                appointmentModel.Employee = _context.Employees.FirstOrDefault(x => x.EmployeeID == appointment.Employee.EmployeeID);
                appointmentModel.UserName = _userManager.GetUserName(User);
                appointmentModel.EmployeeEmail = appointmentModel.Employee.Email;
                appointmentModel.AppointmentStart = appointment.AppointmentStart;
                appointmentModel.AppointmentFinish = appointment.AppointmentFinish;
               // appointment.AppointmentCount = appointment.AppointmentCount;

                if (appointmentModel.AppointmentStart.HasValue)
                {

                    appointment.AppointmentFinish = appointmentModel.AppointmentStart.Value.AddMinutes(15);
                    appointmentModel.AppointmentFinish = appointment.AppointmentFinish;
                    
                    if (_context.Appointments.Where(x =>
                    x.AppointmentStart <= appointment.AppointmentStart &&
                    x.AppointmentFinish >= appointment.AppointmentStart &&
                    x.Employee.EmployeeID == appointment.Employee.EmployeeID).Any())
                    {
                        return RedirectToAction("AppointmentExists");
                    }

                    else if (_context.Appointments.Where(x =>
                     x.AppointmentStart <= appointment.AppointmentFinish &&
                     x.AppointmentFinish >= appointment.AppointmentFinish &&
                     x.Employee.EmployeeID == appointment.Employee.EmployeeID).Any())
                    {
                        return RedirectToAction("AppointmentExists");
                    }


                    Appointment newAppointment = _appointmentRepository.Add(appointmentModel);
                    _context.SaveChanges();

                }

            }
            return RedirectToAction("MyAppointment");
        }


        // Tutaj Pacjent umawia wizytę - jak wybiore lekarza i naciskam - Umów wiytę to wywołuję tę metodę
        public IActionResult Appointment(int id)
        {
            AppointmentViewModel appointmentViewModel = new AppointmentViewModel()
            {
                UserID = _userManager.GetUserId(User),
                Employee = _employeeRepository.GetEmployee(id),
                EmployeeID = _employeeRepository.GetEmployee (id).EmployeeID,
                EmployeeEmail = _employeeRepository.GetEmployee(id).Email,
            };

            return View(appointmentViewModel);
        }


        // Po umówieniu wizyty, Pacjent przechodzi do Podsumowania wizyty - AppointmentDetails
        public ViewResult AppointmentDetails(int id)
        {
            AppointmentDetailsViewModel appointmentDetailsViewModel = new AppointmentDetailsViewModel()
            {
                UserID = _userManager.GetUserId(User),
                Appointment = _appointmentRepository.GetAppointment(id),
                Employee = _employeeRepository.GetEmployee(id),
            };

            return View(appointmentDetailsViewModel);
        }

        // Po umówieniu wizyty, podsumowanie można zapisać do PDF
        public async Task<IActionResult> AppointmentPDF(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var appointment = await _context.Appointments
                .FirstOrDefaultAsync(m => m.AppointmentID == id);
            if (appointment == null)
            {
                return NotFound();
            }

            return new ViewAsPdf(appointment);
        }

        // Tutaj wyświetlają się wizyty tylko dla zalogowanego pacjenta
        public async Task<IActionResult> MyAppointment(int id)
        {
            {
                ApplicationUser user = await GetCurrentUserAsync();
                var appointment = _appointmentRepository.GetAllAppointments()
                    .Where(p => p.UserName == user.UserName)
                    .OrderByDescending(p => p.AppointmentStart);

                ViewBag.TerazJest = DateTime.Now;
                return View(appointment);
            }

        }


        // Tutaj wyświetlają się wizyty tylko dla zalogowanego lekarza
        public async Task<IActionResult> DoctorAppointment(int id)
        {
            ApplicationUser user = await GetCurrentUserAsync();
            var appointment = _appointmentRepository.GetAllAppointments()
                .Where(p => p.EmployeeEmail == user.UserName)
                .OrderByDescending(p => p.AppointmentStart);

            ViewBag.TerazJest = DateTime.Now;
            return View(appointment);
        }

        private Task<ApplicationUser> GetCurrentUserAsync() => _userManager.GetUserAsync(HttpContext.User);

        // Edytuję wizytę
        [HttpGet]
        public ViewResult EditAppointment(int id)
        {
            Appointment appointment = _appointmentRepository.GetAppointment(id);
            AppointmentEditViewModel appointmentEditViewModel = new AppointmentEditViewModel
            {
                AppointmentID = appointment.AppointmentID,
                EmployeeID = appointment.EmployeeID,
                UserName = appointment.UserName,

                AppointmentStart = appointment.AppointmentStart,
                AppointmentFinish = appointment.AppointmentFinish,
            };
            return View(appointmentEditViewModel);
        }

        // Dokonuję zmian w edytowanej wizycie
        [HttpPost]
        public IActionResult EditAppointment(AppointmentEditViewModel model)
        {
            if (ModelState.IsValid)
            {
                Appointment appointment = _appointmentRepository.GetAppointment(model.AppointmentID);
                appointment.EmployeeID = model.EmployeeID;
                appointment.UserName = model.UserName;
                appointment.AppointmentStart = model.AppointmentStart;

                appointment.AppointmentFinish = model.AppointmentStart.Value.AddMinutes(15);
                appointment.AppointmentFinish = appointment.AppointmentFinish;
                model.AppointmentFinish = appointment.AppointmentFinish;


                if (appointment.AppointmentStart < DateTime.Now)
                {
                    return RedirectToAction("AppointmentLate");
                }

                else if (_context.Appointments.Where(x =>
                x.AppointmentStart <= appointment.AppointmentStart &&
                x.AppointmentFinish >= appointment.AppointmentStart).Any())
                {
                    return RedirectToAction("AppointmentExists");
                }

                else if (_context.Appointments.Where(x =>
                x.AppointmentStart <= appointment.AppointmentFinish &&
                x.AppointmentFinish >= appointment.AppointmentFinish).Any())
                {
                    return RedirectToAction("AppointmentExists");
                }

DentalApp/Controllers/EmployeeController.cs
using System;
using System.IO;
using System.Linq;
using DentalApp.DataContext;
using DentalApp.Models;
using DentalApp.Repositories;
using DentalApp.ViewModels;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace DentalApp.Controllers
{
    public class EmployeeController : Controller
    {
    // dependency injection przez konstruktor
        private readonly IEmployeeRepository _employeeRepository;
        private readonly IHostingEnvironment _hostingEnvironment;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly ApplicationDbContext _context;

        public EmployeeController(IEmployeeRepository employeeRepository, IHostingEnvironment hostingEnvironment,
            UserManager<ApplicationUser> userManager, ApplicationDbContext context)
        {
            _employeeRepository = employeeRepository;
            _hostingEnvironment = hostingEnvironment;
            _userManager = userManager;
            _context = context;
        }

        // Lista lekarzy dla pacjentów
        public ViewResult NewList()
        {
            var model = _employeeRepository.GetAllEmployees().Where(p => p.Specialty != "Asystentka");
            return View(model);
        }

        // Lista prcowników dla admina
        public ViewResult List()
        {
            var model = _employeeRepository.GetAllEmployees();
            return View(model);
        }

        public ViewResult Details(int id)
        {
            HomeDetailsViewModel homeDetailsViewModel = new HomeDetailsViewModel()
            {
                Employee = _employeeRepository.GetEmployee(id),
                PageTitle = "Employee Details"
            };

            return View(homeDetailsViewModel);
        }


        [HttpGet]
        public ViewResult Edit(int id)
        {
            Employee employee = _employeeRepository.GetEmployee(id);
            EmployeeEditViewModel employeeEditViewModel = new EmployeeEditViewModel
            {
                EmployeeID = employee.EmployeeID,
                FirstName = employee.FirstName,
                LastName = employee.LastName,
                Specialty = employee.Specialty,
                Email = employee.Email,
                Description = employee.Description,
                ExistingPhotoPath = employee.PhotoPath
            };
            return View(employeeEditViewModel);
        }


        [HttpPost]
        public IActionResult Edit(EmployeeEditViewModel model)
        {
            if (ModelState.IsValid)
            {
                Employee employee = _employeeRepository.GetEmployee(model.EmployeeID);
                employee.FirstName = model.FirstName;
                employee.LastName = model.LastName;
                employee.Specialty = model.Specialty;
                employee.Email = model.Email;
                employee.Description = model.Description;


                if (model.Photo != null)
                {
                    if (model.ExistingPhotoPath != null)
                    {
                        string filePath = Path.Combine(_hostingEnvironment.WebRootPath, "Images", model.ExistingPhotoPath);
                        System.IO.File.Delete(filePath);
                    }
                    employee.PhotoPath = ProcessUploadedFile(model);
                }

                _employeeRepository.Update(employee);

                return RedirectToAction("NewList");
            }
            return View();
        }

        private string ProcessUploadedFile(EmployeeCreateViewModel model)
        {
            string uniqueFileName = null;

            if (model.Photo != null)
            {
                string uploadsFolder = Path.Combine(_hostingEnvironment.WebRootPath, "Images");
                uniqueFileName = Guid.NewGuid().ToString() + "_" + model.Photo.FileName;
                string filePath = Path.Combine(uploadsFolder, uniqueFileName);
                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    model.Photo.CopyTo(fileStream);
                }
            }

            return uniqueFileName;
        }

        [HttpGet]
        public ViewResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(EmployeeCreateViewModel model)
        {
            if (ModelState.IsValid)
            {
                string uniqueFileName = ProcessUploadedFile(model);
                Employee newEmployee = new Employee
                {
                    FirstName = model.FirstName,
                    LastName = model.LastName,
                    Specialty = model.Specialty,
                    Email = model.Email,
                    Description = model.Description,
                    PhotoPath = uniqueFileName
                };

                _employeeRepository.Add(newEmployee);

                return RedirectToAction("details", new { id = newEmployee.EmployeeID });
            }
            return View();
        }

        public Employee Delete(int id)
        {
            Employee employee = _context.Employees.Find(id);
            if (employee != null)
            {
                _context.Employees.Remove(employee);
                _context.SaveChanges();
            }
            return employee;
        }
    }
}

DentalApp/Views/Appointment/Appointment.cshtml
@model DentalApp.ViewModels.AppointmentViewModel
@using Microsoft.AspNetCore.Identity
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

@{
    ViewData["Title"] = "Create";
}

@if (SignInManager.IsSignedIn(User))
{
    <img src="~/Images/Various/assist.jpg" align="left" height="150" width="135" />
    <div class="row">
        <div class="col-md-4">
            <h4>  Umów wizytę @UserManager.GetUserAsync(User).Result.FirstName</h4>
            <br />
            <form asp-controller="Appointment" asp-action="CreateAppointment" asp-route-id="@Model.Employee.EmployeeID" method="post">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <p class="text-white bg-dark">Pacjent</p>
                    <p>Imie: @UserManager.GetUserAsync(User).Result.FirstName</p>
                    <p>Nazwisko: @UserManager.GetUserAsync(User).Result.LastName</p>
                    <p>Email: @UserManager.GetUserAsync(User).Result.Email
                    <p>Pesel: @UserManager.GetUserAsync(User).Result.PeselID
                </div>
                <div class="form-group">
                    <p class="text-white bg-dark">Lekarz</p>
                    <p>LekarzID: @Model.Employee.EmployeeID</p>
                    <p>Imie: @Model.Employee.FirstName</p>
                    <p>Nazwisko: @Model.Employee.LastName</p>
                    <p>Specjalizacja: @Model.Employee.Specialty</p>
                    <p>Email: @Model.Employee.Email</p>
                </div>
                <input type="hidden" asp-for="@Model.Employee.EmployeeID" />
                <input type="hidden" asp-for="@Model.UserID" />
                <div class="form-group">
                    <p class="text-white bg-dark">Data wizyty</p>
                    <label asp-for="AppointmentStart" class="control-label">Proszę podać datę i godzinę wizyty</label>
                    <input asp-for="AppointmentStart" class="form-control" />
                    <span asp-validation-for="AppointmentStart" class="text-danger"></span>
                </div>

                <div class="form-group">

                    <button type="submit" value="save" class="btn btn-outline-primary" method="post">Umawiam</button>
                    <a asp-controller="Employee" asp-action="NewList" class="btn btn-outline-secondary">Powrót</a>
                </div>
            </form>
        </div>
    </div>
}

else
{

    <br>
    <img src="~/Images/Various/assist.jpg" align="left" height="150" width="135" />
    <font size="5">Przed umówieniem wizyty, proszę się zalogować.</font>
    <br>
    <br>
    <font size="3">Czy już się rejestrowałeś? Proszę potwierdzić rejestrację.</font>
    <br>
    <br>
    <br>
    <br>
    <ul class="nav nav-tabs">
        <li class="nav-item">
            <a class="nav-link text-dark" asp-controller="Account" asp-action="Register">Zarejestruj się</a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-dark" asp-controller="Account" asp-action="Login">Zaloguj się</a>
        </li>
        <li class="nav-item">
            <a asp-controller="Employee" asp-action="NewList" class="btn btn-outline-secondary">Powrót</a>
        </li>
    </ul>
}

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

DentalApp/Views/Appointment/CreateAppointment.cshtml
@model DentalApp.ViewModels.AppointmentViewModel
@using Microsoft.AspNetCore.Identity
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

@{
    ViewData["Title"] = "Create";
}

@if (SignInManager.IsSignedIn(User))
{
    <img src="~/Images/Various/assist.jpg" align="left" height="150" width="135" />
    <h4 class="text-primary">  Umów wizytę @UserManager.GetUserAsync(User).Result.FirstName</h4>
    <div class="row">
        <div class="col-md-4">
            <br />
            <form asp-controller="Appointment" asp-action="CreateAppointment" asp-route-id="@Model.Employee.EmployeeID" method="post">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <p class="text-white bg-dark">Lekarz ID</p>
                    <label asp-for="EmployeeID" class="control-label">Proszę podać ID Lekarza</label>
                    <input asp-for="EmployeeID" class="form-control" />
                    <span asp-validation-for="EmployeeID" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <p class="text-white bg-dark">Email pacjenta</p>
                    <label asp-for="UserName" class="control-label">Proszę podać Email pacjenta</label>
                    <input asp-for="UserName" class="form-control" />
                    <span asp-validation-for="UserName" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <p class="text-white bg-dark">Email pacjenta</p>
                    <label asp-for="EmployeeEmail" class="control-label">Proszę podać Email pacjenta</label>
                    <input asp-for="EmployeeEmail" class="form-control" />
                    <span asp-validation-for="EmployeeEmail" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <p class="text-white bg-dark">Data wizyty</p>
                    <label asp-for="AppointmentStart" class="control-label">Proszę podać datę i godzinę wizyty</label>
                    <input asp-for="AppointmentStart" class="form-control" />
                    <span asp-validation-for="AppointmentStart" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <button type="submit" class="btn btn-outline-primary">Umawiam</button>
                    @*<button type="submit" asp-controller="Wizyta" asp-action="WizytaDetails" asp-route-id="@Model.Lekarz.LekarzID" class="btn btn-primary">Umawiam</button>*@
                    <a asp-controller="Employee" asp-action="NewList" class="btn btn-outline-secondary">Powrót</a>
                </div>
            </form>
        </div>
    </div>
}

else
{
    <br>
    <img src="~/Images/img1.jpg" align="left" height="200" width="250" />
    <font size="5">Przed umówieniem wizyty, proszę się zalogować.</font>
    <br>
    <br>
    <font size="3">Czy już się rejestrowałeś? Proszę potwierdzić rejestrację.</font>
    <br>
    <br>
    <br>
    <br>
    <ul class="nav nav-tabs">
        <li class="nav-item">
            <a class="nav-link text-dark" asp-controller="Account" asp-action="Register">Zarejestruj się</a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-dark" asp-controller="Account" asp-action="Login">Zaloguj się</a>
        </li>
        <li class="nav-item">
            <a asp-controller="NewLekarz" asp-action="NewIndex" class="btn btn-outline-secondary">Powrót</a>
        </li>
    </ul>
}

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

DentalApp/Views/Appointment/DetailAppointment.cshtml
@model DentalApp.Models.Appointment
@using Microsoft.AspNetCore.Identity
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

<img src="~/Images/Various/assist.jpg" align="left" height="150" width="135" />
<h5>Pacjent: @Html.DisplayFor(model => model.UserName)</h5>
<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.EmployeeID)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.EmployeeID)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.UserName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.UserName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.AppointmentStart)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.AppointmentStart)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.AppointmentFinish)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.AppointmentFinish)
        </dd>
    </dl>
</div>
<div>
    <a asp-controller="Appointment" asp-action="EditAppointment" class="btn btn-primary btn-sm" asp-route-id="@Model.AppointmentID">Edytuj</a>
    <a @*asp-controller="Appointment" asp-action="MyAppointment"*@ class="btn btn-outline-secondary btn-sm" onclick="history.go(-1)" >Powrót</a>
    <a asp-controller="Appointment" asp-action="AppointmentPDF" class="btn btn-outline-secondary btn-sm" asp-route-id="@Model.AppointmentID">Wydruk do PDF</a>
</div>

DentalApp/Views/Appointment/DoctorAppointment.cshtml
@model IEnumerable<Appointment>
@using Microsoft.AspNetCore.Identity
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

@{
    ViewData["Title"] = "Doctor Appointment";
}

<html>
<body>
    <table class="table">
        <thead class="thead-dark">
            <tr>
                <th scope="col">Wizyta </th>
                <th scope="col">Lekarz </th>
                <th scope="col">Email pacjenta </th>
                <th scope="col">Start wizyty </th>
                <th scope="col">Koniec wizyty </th>
                <th scope="col">Co chcesz zrobić? </th>
            </tr>
        </thead>
        <tbody>
            <!--Dla każdego obiektu wizyty w Modelu-->
            @foreach (var appointment in Model)
            {
            <tr>
                <td>@appointment.AppointmentID</td>
                <td>@appointment.EmployeeID</td>
                <td>@appointment.UserName</td>
                <td>@appointment.AppointmentStart</td>
                <td>@appointment.AppointmentFinish</td>
                <td>
                    <a class="btn btn-outline-secondary btn-sm" asp-controller="Appointment" asp-action="EditAppointment" asp-route-id="@appointment.AppointmentID">Edytuj</a><font color="white">|</font>
                    <a class="btn btn-outline-secondary btn-sm" asp-controller="Appointment" asp-action="DetailAppointment" asp-route-id="@appointment.AppointmentID">Szczegóły</a><font color="white">|</font>
                    <a asp-controller="Appointment" asp-action="DeleteAppointment" asp-route-id="@appointment.AppointmentID" class="btn btn-outline-danger btn-sm"
                       onclick="return confirm('Czy na pewno chcesz usunąć wizytę: @appointment.AppointmentID ?')">Usuń</a><font color="white">|</font>
                </td>
            </tr>
            }
        </tbody>
    </table>
</body>
</html>

DentalApp/Views/Appointment/GetAllAppointments.cshtml
@model IEnumerable<Appointment>
@using Microsoft.AspNetCore.Identity
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager


<html>
<body>
    <table class="table">
        <thead class="thead-dark">
            <tr>
                <th scope="col">Wizyta</th>
                <th scope="col">Lekarz</th>
                <th scope="col">Email pacjenta</th>
                <th scope="col">Start wizyty </th>
                <th scope="col">Koniec wizyty </th>
                <th scope="col">Co chcesz zrobić? </th>
            </tr>
        </thead>
        <tbody>
            <!--Dla każdego obiektu wizyty w Modelu-->
            @foreach (var appointment in Model)
            {
                <tr>
                    <td>@appointment.AppointmentID</td>
                    <td>@appointment.EmployeeID</td>
                    <td>@appointment.UserName</td>
                    <td>@appointment.AppointmentStart</td>
                    <td>@appointment.AppointmentFinish</td>
                    <td>
                        <a class="btn btn-outline-secondary btn-sm" asp-controller="Appointment" asp-action="EditAppointment" asp-route-id="@appointment.AppointmentID">Edytuj</a><font color="white">|</font>
                        <a class="btn btn-outline-secondary btn-sm" asp-controller="Appointment" asp-action="DetailAppointment" asp-route-id="@appointment.AppointmentID">Szczegóły</a><font color="white">|</font>
                        <a asp-controller="Appointment" asp-action="DeleteAppointment" asp-route-id="@appointment.AppointmentID" class="btn btn-outline-danger btn-sm"
                           onclick="return confirm('Czy na pewno chcesz usunąć wizytę: @appointment.AppointmentID ?')">Usuń</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</body>
</html>